import React, { useEffect, useRef, useState } from 'react';
import { Bell, Camera, Check, ChevronRight, CloudRain, Droplets, Leaf, MapPin, Search, Sprout, Sun, Upload, UserRound, Wind, X } from 'lucide-react';
import { Screen, Task, Language } from '../types';
import { useGeolocation } from '../hooks/useGeolocation';
import { isDiagnosisUnavailable } from '../utils/diagnosisDisplay';

interface DashboardProps { onNavigate: (screen: Screen) => void; onFileSelect: (file: File) => void; onAddTask?: (task: Omit<Task, 'id' | 'completed'>) => void; language: Language; onToggleLanguage: (lang?: Language) => void; onCameraOpen: () => void; lastDiagnosis?: any; }
interface WeatherSummaryData { temperature: number; humidity: number; rainVolume: number; rainProbability: number; maxRainProbability: number; windSpeed: number; weatherCode: number; summary: string; advice: string[]; farmingIndex: 'Favorable' | 'Caution Required' | 'Hazardous'; }

const forecast = [{ day: 'Today', temperature: '35°', icon: 'partly' }, { day: 'Tomorrow', temperature: '36°', icon: 'sun' }, { day: 'Wed', temperature: '30°', icon: 'rain' }, { day: 'Thu', temperature: '28°', icon: 'storm' }, { day: 'Fri', temperature: '31°', icon: 'partly' }];

function ForecastIcon({ type }: { type: string }) { return type === 'rain' || type === 'storm' ? <CloudRain size={24} className="text-emerald-400" /> : <Sun size={24} className="text-amber-400" />; }

export const Dashboard: React.FC<DashboardProps> = ({ onNavigate, onFileSelect, onCameraOpen, language, lastDiagnosis }) => {
  const { latitude, longitude, loading: locationLoading, error: locationError } = useGeolocation();
  const [locationName, setLocationName] = useState('Ludhiana, Punjab');
  const [weather, setWeather] = useState<WeatherSummaryData | null>(null);
  const [weatherLoading, setWeatherLoading] = useState(false);
  const [showUpload, setShowUpload] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (!latitude || !longitude) return;
    setWeatherLoading(true);
    fetch(`https://nominatim.openstreetmap.org/reverse?format=json&lat=${latitude}&lon=${longitude}`)
      .then((response) => response.json()).then((data) => { const address = data.address || {}; const city = address.city || address.town || address.village || address.county; if (city && address.state) setLocationName(`${city}, ${address.state}`); }).catch(() => undefined);
    fetch('/api/weather-summary', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ latitude, longitude, language }) })
      .then((response) => response.ok ? response.json() : Promise.reject(new Error('Weather unavailable'))).then((data: WeatherSummaryData) => setWeather(data)).catch(() => setWeather(null)).finally(() => setWeatherLoading(false));
  }, [latitude, longitude, language]);

  const temperature = weather ? Math.round(weather.temperature) : 32;
  const humidity = weather ? Math.round(weather.humidity) : 65;
  const wind = weather ? Math.round(weather.windSpeed) : 12;
  const rainLikely = weather ? weather.rainProbability >= 40 : false;
  const sprayRisk = weather?.farmingIndex === 'Hazardous' || rainLikely ? 'High' : weather?.farmingIndex === 'Caution Required' ? 'Medium' : 'Low';
  const sprayCopy = sprayRisk === 'Low' ? 'Optimal conditions for spraying organic protocols today. Wind speeds are stable.' : 'Review weather conditions before applying any spray or nutrient treatment.';
  const diagnosisUnavailable = isDiagnosisUnavailable(lastDiagnosis);
  const handleUpload = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) onFileSelect(file); event.target.value = ''; setShowUpload(false); };

  return <main className="agro-dashboard min-h-screen bg-[#f8f9fa] pb-28 text-[#191c1d]">
    <header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-[#e1e3e4] bg-[#f8f9fa]/90 px-4 backdrop-blur-xl sm:px-6"><div className="flex min-w-0 items-center gap-3"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-sm bg-[#e6f3ed] text-[#003527]" aria-label="AgroCare logo"><Sprout size={20} /></div><h1 className="truncate font-display text-2xl font-semibold tracking-tight text-[#003527]">Dashboard</h1></div><div className="flex items-center gap-1 sm:gap-2"><button className="flex h-12 w-12 items-center justify-center rounded-full text-[#404944] hover:bg-[#edeeef]" aria-label="Search" title="Search"><Search size={22} /></button><button className="flex h-12 w-12 items-center justify-center rounded-full text-[#404944] hover:bg-[#edeeef]" aria-label="Notifications" title="Notifications"><Bell size={21} /></button><button onClick={() => onNavigate('profile')} className="ml-1 flex h-9 w-9 items-center justify-center rounded-full bg-[#003527] text-white" aria-label="Profile"><UserRound size={18} /></button></div></header>
    <div className="mx-auto flex w-full max-w-5xl flex-col gap-4 px-4 pt-4 sm:px-6 lg:px-8">
      <section className="relative overflow-hidden rounded-[28px] border border-[#e1e3e4] bg-gradient-to-b from-[#dce9f0] via-[#f3f4f0] to-[#f3f4f5] p-6 shadow-[0_8px_24px_rgba(0,53,39,0.05)] sm:p-8" aria-label="Current weather"><div className="pointer-events-none absolute inset-0 opacity-35" style={{ backgroundImage: 'linear-gradient(170deg, rgba(255,255,255,.9), transparent 48%, rgba(255,255,255,.85)), url("https://images.unsplash.com/photo-1499346030926-9a72daac6c63?auto=format&fit=crop&w=1200&q=75")', backgroundSize: 'cover', backgroundPosition: 'center' }} /><div className="relative"><div className="flex items-center gap-2 text-lg text-[#404944]"><MapPin size={19} /><span>{locationLoading ? 'Locating farm...' : locationError ? 'Location unavailable' : locationName}</span></div><div className="mt-7 flex items-end justify-between gap-4"><div><div className="font-display text-[64px] font-bold leading-none tracking-tight sm:text-[72px]">{weatherLoading ? '--' : `${temperature}°`}</div><div className="mt-2 text-lg text-[#404944]">{rainLikely ? 'Rain likely' : 'Partly Cloudy'}</div></div><Sun size={58} strokeWidth={1.8} className="mb-2 text-[#f9bd22]" /></div><div className="mt-7 grid grid-cols-3 divide-x divide-[#d9dadb] rounded-2xl bg-white/70 p-3 text-center backdrop-blur-md"><div><Droplets size={20} className="mx-auto text-[#95d3ba]" /><strong className="mt-1 block text-lg font-medium">{humidity}%</strong><span className="text-xs text-[#404944]">Humidity</span></div><div><Wind size={20} className="mx-auto text-[#f9bd22]" /><strong className="mt-1 block text-lg font-medium">{wind} km/h</strong><span className="text-xs text-[#404944]">Wind</span></div><div><Sun size={20} className="mx-auto text-[#fd9e70]" /><strong className="mt-1 block text-lg font-medium">8.4</strong><span className="text-xs text-[#404944]">UV Index</span></div></div></div></section>
      <section className={`rounded-2xl p-5 text-[#80bea6] shadow-[0_5px_16px_rgba(0,53,39,0.12)] ${sprayRisk === 'Low' ? 'bg-[#064e3b]' : 'bg-[#584000]'}`} aria-label="Spray risk"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-[#b0f0d6] text-[#002117]"><Leaf size={22} /></div><strong className="text-lg">Spray Risk: {sprayRisk}</strong></div><Check size={22} className="opacity-70" /></div><p className="mt-4 max-w-2xl text-lg leading-7">{sprayCopy}</p></section>
      <section aria-label="7-day forecast"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-medium">7-Day Forecast</h2><button onClick={() => onNavigate('calendar')} className="flex min-h-12 items-center gap-1 text-base text-[#003527]">Detailed <ChevronRight size={17} /></button></div><div className="flex gap-3 overflow-x-auto pb-1 scrollbar-hide">{forecast.map((day, index) => <div key={day.day} className={`flex h-[110px] min-w-[76px] shrink-0 flex-col items-center justify-between rounded-xl p-3 ${index === 0 ? 'bg-[#003527] text-white' : 'bg-[#edeeef] text-[#191c1d]'}`}><span className="text-sm">{day.day}</span><ForecastIcon type={day.icon} /><strong className="text-base font-medium">{day.temperature}</strong></div>)}</div></section>
      <section aria-label="Smart advisories"><div className="mb-3 flex items-center gap-3"><Sprout size={23} className="text-[#003527]" /><h2 className="text-lg font-medium">Smart Advisories</h2></div><div className="space-y-3"><Advisory accent="#fd9e70" icon={<Droplets size={22} className="text-[#944a23]" />} label="UPCOMING WEATHER" title="Heavy Rain Alert" text="Significant rainfall expected in 48 hours. Suggest completing any planned nutrient treatments today to avoid runoff." /><Advisory accent="#f9bd22" icon={<Leaf size={22} className="text-[#3c2b00]" />} label="CROP HEALTH RISK" title="High Humidity Alert" text={`Elevated humidity levels (${humidity}%+) may increase fungal risk. Closely monitor tomato and pepper crops in your farm.`} /></div></section>
      <section className="flex flex-col gap-3 rounded-2xl border border-[#bfc9c3] bg-white p-4 shadow-sm sm:flex-row sm:items-center sm:justify-between" aria-label="Crop diagnosis"><div><div className="flex items-center gap-2 text-[#003527]"><Camera size={20} /><h2 className="text-lg font-medium">Crop health scan</h2></div><p className="mt-1 text-sm text-[#404944]">{lastDiagnosis ? (diagnosisUnavailable ? 'Retake a clear photo for a reliable result.' : 'Your latest diagnosis is ready to review.') : 'Capture a leaf photo for an AI diagnosis.'}</p></div><div className="flex gap-2"><button onClick={onCameraOpen} className="flex min-h-12 items-center justify-center gap-2 rounded-lg bg-[#003527] px-4 font-medium text-white"><Camera size={18} /> Scan</button><button onClick={() => setShowUpload(true)} className="flex min-h-12 items-center justify-center gap-2 rounded-lg border border-[#bfc9c3] px-4 font-medium text-[#003527]"><Upload size={18} /> Upload</button></div><input ref={fileInputRef} type="file" accept="image/*" onChange={handleUpload} className="hidden" /></section>
    </div>
    {showUpload && <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/30 p-4 sm:items-center" role="dialog" aria-modal="true" aria-label="Upload crop photo"><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Upload crop photo</h2><button onClick={() => setShowUpload(false)} className="flex h-12 w-12 items-center justify-center rounded-full hover:bg-[#edeeef]" aria-label="Close upload dialog"><X size={20} /></button></div><button onClick={() => fileInputRef.current?.click()} className="mt-5 flex min-h-14 w-full items-center justify-center gap-2 rounded-lg bg-[#003527] font-medium text-white"><Upload size={19} /> Choose image</button></div></div>}
  </main>;
};

function Advisory({ accent, icon, label, title, text }: { accent: string; icon: React.ReactNode; label: string; title: string; text: string }) { return <article className="relative overflow-hidden rounded-2xl bg-[#f3f4f5] p-5 pl-7 shadow-sm"><div className="absolute bottom-0 left-0 top-0 w-1" style={{ backgroundColor: accent }} /><div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-white">{icon}</div><div><span className="text-[11px] font-medium tracking-wider text-[#944a23]">{label}</span><h3 className="mt-1 text-lg font-medium">{title}</h3><p className="mt-3 max-w-2xl text-base leading-7 text-[#404944]">{text}</p><button className="mt-4 min-h-11 rounded-lg bg-white px-4 text-sm font-medium shadow-sm">Save Advisory</button></div></div></article>; }
