import { CropPrice, Supplier, Discussion, Task, RecommendedCrop } from './types';

export const CROP_PRICES: CropPrice[] = [
  {
    id: '1',
    name: 'Wheat',
    nameHi: 'गेहूँ',
    nameKn: 'ಗೋಧಿ',
    price: 2275,
    change: 25,
    changePercent: 1.1,
    mandi: 'Azadpur Mandi',
    trend: 'up',
    icon: '🌾',
    category: 'Grains',
  },
  {
    id: '2',
    name: 'Onion',
    nameHi: 'प्याज',
    nameKn: 'ಈರುಳ್ಳಿ',
    price: 1400,
    change: -40,
    changePercent: 2.8,
    mandi: 'Nasik Mandi',
    trend: 'down',
    icon: '🧅',
    category: 'Vegetables',
  },
  {
    id: '3',
    name: 'Mustard',
    nameHi: 'सरसों',
    nameKn: 'ಸಾಸಿವೆ',
    price: 5450,
    change: 0,
    changePercent: 0.0,
    mandi: 'Local Mandi',
    trend: 'neutral',
    icon: '🟡',
    category: 'Oilseeds',
  },
  {
    id: '4',
    name: 'Potato',
    nameHi: 'आलू',
    nameKn: 'ಆಲೂಗಡ್ಡೆ',
    price: 850,
    change: 15,
    changePercent: 1.8,
    mandi: 'Agra Mandi',
    trend: 'up',
    icon: '🥔',
    category: 'Vegetables',
  },
];

export const SUPPLIERS: Supplier[] = [
  {
    id: '1',
    name: 'AgroInput Solutions',
    distance: '2.5 km',
    status: 'open',
    rating: 4.8,
    reviews: 124,
    tags: ['Mancozeb', 'Recommended'],
    verified: true,
    phone: '+919876543210',
    address: 'Near Old Bus Stand, Market Road',
  },
  {
    id: '2',
    name: 'Kisan Seva Kendra',
    distance: '4.2 km',
    status: 'closing',
    rating: 4.2,
    reviews: 56,
    tags: ['General Seeds', 'Tools'],
    verified: false,
    phone: '+919876543211',
    address: 'Main Gate, APMC Yard',
  },
  {
    id: '3',
    name: 'Village Organic Hub',
    distance: '8.5 km',
    status: 'closed',
    rating: 3.9,
    reviews: 12,
    tags: ['Organic'],
    verified: false,
    phone: '+919876543212',
    address: 'Shop No. 4, Gram Panchayat Road',
  },
];

export const DISCUSSIONS: Discussion[] = [
  {
    id: '1',
    author: 'Ramesh Singh',
    authorInitials: 'RS',
    authorReputation: 250,
    authorBadge: 'Expert Farmer',
    location: 'Ludhiana, Punjab',
    time: '2h ago',
    title: 'Natural ways to stop aphids in okra?',
    content: 'My okra crop is heavily infested with aphids. I tried neem oil but it rained right after. Looking for organic solutions that stick better during monsoon.',
    tags: ['Okra', 'PestControl'],
    likes: 24,
    downvotes: 2,
    hasUpvoted: false,
    hasDownvoted: false,
    comments: 8,
    isReported: false,
  },
  {
    id: '2',
    author: 'Vijay Patel',
    authorInitials: 'VP',
    authorReputation: 45,
    location: 'Surat, Gujarat',
    time: '5h ago',
    title: 'Yellow spots on corn leaves',
    content: 'Noticed these yellow spots spreading rapidly on my corn field. Is this rust or blight? Should I spray fungicide immediately?',
    tags: ['Corn', 'Disease'],
    likes: 15,
    downvotes: 0,
    hasUpvoted: true,
    hasDownvoted: false,
    comments: 12,
    isReported: false,
  },
  {
    id: '3',
    author: 'Anita Sharma',
    authorInitials: 'AS',
    authorReputation: 120,
    authorBadge: 'Helpful Member',
    location: 'Pune, Maharashtra',
    time: '1d ago',
    title: 'Which fertilizer is best for early stage tomatoes?',
    content: 'I am planning to use organic fertilizers for my new tomato crop. What do you all recommend?',
    tags: ['Tomato', 'Fertilizers'],
    poll: {
      question: 'Which organic fertilizer works best for tomatoes?',
      options: [
        { id: 'p1', text: 'Vermicompost', votes: 45 },
        { id: 'p2', text: 'Cow Dung Manure', votes: 30 },
        { id: 'p3', text: 'Neem Cake', votes: 15 },
        { id: 'p4', text: 'Bone Meal', votes: 10 }
      ],
      totalVotes: 100,
      userVotedOption: 'p1'
    },
    likes: 42,
    downvotes: 4,
    hasUpvoted: false,
    hasDownvoted: false,
    comments: 18,
    isReported: false,
  }
];

export const TASKS: Task[] = [
  {
    id: '1',
    title: 'Water Seedlings',
    titleHi: 'पौधों को पानी दें',
    titleKn: 'ಸಸಿಗಳಿಗೆ ನೀರು ಹಾಕಿ',
    description: 'Ensure soil is moist, not waterlogged.',
    icon: 'Droplets',
    color: 'blue',
    completed: true,
  },
  {
    id: '2',
    title: 'Check for Pests',
    titleHi: 'कीड़ों की जाँच करें',
    titleKn: 'ಕೀಟಗಳಿಗಾಗಿ ಪರೀಕ್ಷಿಸಿ',
    description: 'Inspect under leaves for aphids.',
    icon: 'Bug',
    color: 'red',
    completed: false,
    urgent: true,
  },
  {
    id: '3',
    title: 'Apply Compost',
    titleHi: 'खाद डालें',
    titleKn: 'ಗೊಬ್ಬರ ಹಾಕಿ',
    description: 'Prepare field #2 for wheat sowing.',
    icon: 'Sprout',
    color: 'green',
    completed: false,
  },
];

export const RECOMMENDED_CROPS: RecommendedCrop[] = [
  {
    id: '1',
    name: 'Tomato',
    nameHi: 'टमाटर',
    nameKn: 'ಟೊಮೆಟೊ',
    status: 'High Yield Potential',
    planting: 'Mid-Sep to Mid-Oct (Nursery) / Oct-Nov (Transplant)',
    harvest: 'Late Jan to Feb',
    icon: '🍅',
    color: 'orange',
    actionEn: 'Prepare soil beds and start sowing seeds in nursery. Apply baseline compost.',
    actionHi: 'मिट्टी की क्यारियाँ तैयार करें और नर्सरी में बीज बोना शुरू करें। बेसलाइन खाद डालें।',
    actionKn: 'ಮಣ್ಣಿನ ಹಾಸಿಗೆಗಳನ್ನು ತಯಾರಿಸಿ ಮತ್ತು ನರ್ಸರಿಯಲ್ಲಿ ಬೀಜಗಳನ್ನು ಬಿತ್ತಲು ಪ್ರಾರಂಭಿಸಿ. ಕಾಂಪೋಸ್ಟ್ ಹಾಕಿ.'
  },
  {
    id: '2',
    name: 'Wheat',
    nameHi: 'गेहूं',
    nameKn: 'ಗೋಧಿ',
    status: 'Optimal Conditions',
    planting: 'Late Oct to Mid-Nov',
    harvest: 'March to Mid-April',
    icon: '🌾',
    color: 'yellow',
    actionEn: 'Ensure deep ploughing and field leveling. Test soil moisture before sowing.',
    actionHi: 'गहरी जुताई और खेत को समतल करना सुनिश्चित करें। बुवाई से पहले मिट्टी की नमी का परीक्षण करें।',
    actionKn: 'ಆಳವಾದ ಉಳುಮೆ ಮತ್ತು ಭೂಮಿಯನ್ನು ಸಮತಟ್ಟು ಮಾಡುವುದನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ. ಬಿತ್ತನೆ ಮಾಡುವ ಮೊದಲು ಮಣ್ಣಿನ ತೇವಾಂಶವನ್ನು ಪರೀಕ್ಷಿಸಿ.'
  },
];
